import { Sandbox } from "@cloudflare/sandbox";
import { GitHubApp } from "@sherpa/github";
import { reviewJobSchema, type ReviewJob } from "@sherpa/schemas";
import { handleReviewOutbound, type OutboundPolicy } from "./outbound";

export { ContainerProxy } from "@cloudflare/sandbox";
/** Narrow adapter: concrete deployed bindings are generated by wrangler types. */
type AuthenticationEnvironment = { GITHUB_APP_ID: string; GITHUB_PRIVATE_KEY: string };

export class ReviewSandbox extends Sandbox<AuthenticationEnvironment> {
  enableInternet = false;
  sleepAfter = "5m";
  async beginPreparation(input: ReviewJob): Promise<void> {
    const job = reviewJobSchema.parse(input);
    const existing = await this.ctx.storage.get<OutboundPolicy>("review-policy");
    if (existing) throw new Error("SANDBOX_ALREADY_BOUND");
    const policy: OutboundPolicy = { job, phase: "git", expiresAt: Date.now() + 300000 };
    await this.ctx.storage.put("review-policy", policy);
    await this.setOutboundHandler("reviewPolicy", policy);
  }
  async endPreparation(): Promise<void> {
    const policy = await this.ctx.storage.get<OutboundPolicy>("review-policy");
    if (!policy) throw new Error("SANDBOX_NOT_BOUND");
    policy.phase = "closed";
    policy.expiresAt = 0;
    await this.ctx.storage.put("review-policy", policy);
    await this.setOutboundHandler("reviewPolicy", policy);
  }
  async setPackageAccess(enabled: boolean): Promise<void> {
    const policy = await this.ctx.storage.get<OutboundPolicy>("review-policy");
    if (!policy || policy.phase === "git") throw new Error("PREPARATION_NOT_FINISHED");
    policy.phase = enabled ? "packages" : "closed";
    policy.expiresAt = enabled ? Date.now() + 180000 : 0;
    await this.ctx.storage.put("review-policy", policy);
    await this.setOutboundHandler("reviewPolicy", policy);
  }
}
ReviewSandbox.outbound = () => new Response("Outbound request denied", { status: 403 });
ReviewSandbox.outboundHandlers = {
  reviewPolicy: async (
    request: Request,
    env: AuthenticationEnvironment,
    context: { params?: unknown },
  ) =>
    handleReviewOutbound(request, context.params, async (job) =>
      new GitHubApp({
        appId: env.GITHUB_APP_ID,
        privateKey: env.GITHUB_PRIVATE_KEY,
      }).installationToken(job, "read"),
    ),
};
